@startuml classes

!theme mimeograph

top to bottom direction

hide members

hide circle

skinparam roundcorner 10

skinparam noteFontSize 10
skinparam noteBorderThickness 1
skinparam noteMargin 2
skinparam notePadding 2

skinparam nodesep 10
skinparam ranksep 30

set namespaceSeparator none

'--------------------------------------
' Classes
'--------------------------------------
class "Action" as game.actions.Action {
  {abstract}perform(engine: Engine, entity: Entity) -> None
}

class "ActionWithDirection" as game.actions.ActionWithDirection #e0e0d0 {
  dx : int
  dy : int
}

class "BaseAI" as game.components.ai.BaseAI #e0e0d0 {
  {abstract}perform(engine: Engine, entity: Entity) -> None
}

class "BumpAction" as game.actions.BumpAction #e0e0d0 {
  perform(engine: Engine, entity: Entity) -> None
}

class "Engine" as game.engine.Engine {
  event_handler
  fading_memory : bool
  game_map
  memory : int
  player
  handle_enemy_turns() -> None
  handle_events(events: Iterable[Any]) -> None
  render(console: Console, context: Context) -> None
  run(context: Context, console: Console) -> None
  update_fov(radius: int) -> None
}

class "Entity" as game.entity.Entity {
  ai : BaseAI | None
  blocks_movement : bool
  char : str
  color : tuple[int, int, int]
  name : str
  stays_visible : bool
  x : int
  y : int
  move(dx: int, dy: int) -> None
  set_position(x: int, y: int) -> None
  spawn(game_map: GameMap, x: int, y: int) -> Entity
}

class "EscapeAction" as game.actions.EscapeAction {
  perform(engine: Engine, entity: Entity) -> None
}

class "EventHandler" as game.input_handlers.EventHandler {
  dispatch(event: tcod.event.Event) -> Action | None
  event_keydown(event: tcod.event.KeyDown) -> Action | None
  event_quit(event: tcod.event.Quit) -> Action | None
}

class "GameMap" as game.map.game_map.GameMap {
  entities : set[Entity]
  explored : ndarray
  height : int
  memory : ndarray
  tiles : ndarray
  visible : ndarray
  width : int
  get_blocking_entity_at(x: int, y: int) -> Entity | None
  in_bounds(x: int, y: int) -> bool
  render(console: Console) -> None
}

class "HostileEnemy" as game.components.ai.HostileEnemy #e0e0d0 {
  perform(engine: Engine, entity: Entity) -> None
}

class "MeleeAction" as game.actions.MeleeAction #e0e0d0 {
  perform(engine: Engine, entity: Entity) -> None
}

class "MovementAction" as game.actions.MovementAction {
  perform(engine: Engine, entity: Entity) -> None
}

class "RectangularRoom" as game.map.map_generator.RectangularRoom {
  center : tuple[int, int]
  inner : tuple[slice, slice]
  x1 : int
  x2
  y1 : int
  y2
  intersects(other: RectangularRoom) -> bool
}

class "WaitAction" as game.actions.WaitAction {
  {abstract}perform(engine: Engine, entity: Entity) -> None
}

'--------------------------------------
' Relations
'--------------------------------------

game.actions.ActionWithDirection --|> game.actions.Action
game.actions.BumpAction --|> game.actions.ActionWithDirection
game.actions.EscapeAction --|> game.actions.Action
game.actions.MeleeAction --|> game.actions.ActionWithDirection
game.actions.MovementAction --|> game.actions.ActionWithDirection
game.actions.WaitAction --|> game.actions.Action
game.components.ai.HostileEnemy --|> game.components.ai.BaseAI
game.entity.Entity --* game.map.game_map.GameMap : entities
game.input_handlers.EventHandler --* game.engine.Engine : event_handler
game.entity.Entity --o game.engine.Engine : player
game.map.game_map.GameMap --o game.engine.Engine : game_map

'--------------------------------------
' Order Rules
'--------------------------------------

game.actions.Action -[hidden]down- game.actions.ActionWithDirection
game.actions.Action -[hidden]down- game.actions.WaitAction
game.actions.Action -[hidden]down- game.actions.EscapeAction

game.actions.ActionWithDirection -[hidden]down- game.actions.BumpAction
game.actions.ActionWithDirection -[hidden]down- game.actions.MeleeAction
game.actions.ActionWithDirection -[hidden]down- game.actions.MovementAction

game.components.ai.BaseAI -[hidden]down- game.components.ai.HostileEnemy

game.engine.Engine -[hidden]down-  game.input_handlers.EventHandler
game.engine.Engine -[hidden]down-  game.map.game_map.GameMap

game.map.game_map.GameMap -[hidden]down- game.entity.Entity

game.map.game_map.GameMap -[hidden]down- game.map.map_generator.RectangularRoom

@enduml
