@startuml classes

!theme mimeograph

top to bottom direction

hide members

hide circle

skinparam roundcorner 10

skinparam noteFontSize 10
skinparam noteBorderThickness 1
skinparam noteMargin 2
skinparam notePadding 2

skinparam nodesep 10
skinparam ranksep 30

set namespaceSeparator none

'--------------------------------------
' Classes
'--------------------------------------

class "Action" as game.actions.Action {
}

class "Engine" as game.engine.Engine #e0e0d0 {
}

class "Entity" as game.entity.Entity #e0e0d0 {
}

class "EscapeAction" as game.actions.EscapeAction {
}

class "EventHandler" as game.input_handlers.EventHandler {
}

class "GameMap" as game.game_map.GameMap #e0e0d0 {
}

class "MovementAction" as game.actions.MovementAction {
}

class "WaitAction" as game.actions.WaitAction {
}

'--------------------------------------
' Relations
'--------------------------------------

game.actions.EscapeAction --|> game.actions.Action
game.actions.MovementAction --|> game.actions.Action
game.actions.WaitAction --|> game.actions.Action
game.entity.Entity --o "*" game.engine.Engine : entities
game.entity.Entity --o game.engine.Engine : player
game.game_map.GameMap --o game.engine.Engine : game_map
game.input_handlers.EventHandler --o game.engine.Engine : event_handler

'--------------------------------------
' Order Rules
'--------------------------------------

game.actions.Action -[hidden]down- game.actions.MovementAction
game.actions.Action -[hidden]down- game.actions.WaitAction
game.actions.Action -[hidden]down- game.actions.EscapeAction

game.engine.Engine -[hidden]down-  game.input_handlers.EventHandler
game.engine.Engine -[hidden]down-  game.entity.Entity
game.engine.Engine -[hidden]down-  game.game_map.GameMap

@enduml
