@startuml classes

!theme mimeograph

top to bottom direction

hide members

hide circle

skinparam roundcorner 10

skinparam noteFontSize 10
skinparam noteBorderThickness 1
skinparam noteMargin 2
skinparam notePadding 2

set namespaceSeparator none

'--------------------------------------
' Classes
'--------------------------------------

class "BaseAI" as game.entities.components.ai.BaseAI {
  {abstract}perform(engine: Engine, entity: Entity) -> None
}

class "Entity" as game.entities.entity.Entity {
  ai : BaseAI | None
  blocks_movement : bool
  char : str
  color : tuple[int, int, int]
  name : str
  stays_visible : bool
  x : int
  y : int
  move(dx: int, dy: int) -> None
  set_position(x: int, y: int) -> None
  spawn(game_map: GameMap, x: int, y: int) -> Entity
}

class "HostileEnemy" as game.entities.components.ai.HostileEnemy {
  perform(engine: Engine, entity: Entity) -> None
}

'--------------------------------------
' Relations
'--------------------------------------

game.entities.components.ai.HostileEnemy --|> game.entities.components.ai.BaseAI

'--------------------------------------
' Order Rules
'--------------------------------------

game.entities.components.ai.BaseAI -[hidden]down- game.entities.components.ai.HostileEnemy


@enduml
